import type {
  Company, Tender, Bid, Contract, Document, Evidence,
  Partner, Buyer, CalendarEvent, DashboardStats, ReadinessProfile
} from "@/types"

export const DEMO_COMPANY: Company = {
  id: "demo-co-001",
  name: "Greenfield Infrastructure Ltd",
  sector: "Construction & Highways",
  services: ["Highway maintenance", "Road resurfacing", "Line marking", "Drainage", "Winter maintenance"],
  turnover: 2_800_000,
  employees: 42,
  regions: ["North West", "Yorkshire & Humber", "East Midlands"],
  insurance: ["public-liability", "employers-liability", "professional-indemnity", "vehicle"],
  policies: ["health-safety", "equal-opportunities", "environmental", "gdpr-data-protection", "modern-slavery"],
  accreditations: ["iso-9001", "iso-14001", "iso-45001", "safe-contractor", "constructionline"],
  previousPublicSectorWork: true,
  preferredContractValue: "500k-1m",
  interests: ["highways", "construction", "maintenance", "facilities"],
  readinessScore: 72,
}

export const DEMO_READINESS: ReadinessProfile = {
  overall: 72,
  creditScore: 68,
  lastChecked: "2026-06-15",
  areas: [
    { id: "insurance", name: "Insurance", status: "green", score: 90, issues: [], actions: [] },
    { id: "policies", name: "Policies & Procedures", status: "amber", score: 65, issues: ["GDPR policy needs updating (2024 version)"], actions: ["Update GDPR policy to 2025 ICO guidelines"] },
    { id: "accreditations", name: "Accreditations", status: "green", score: 80, issues: [], actions: ["Consider adding Cyber Essentials for IT contracts"] },
    { id: "cyber", name: "Cyber & Security", status: "amber", score: 50, issues: ["No Cyber Essentials certificate", "No IT security policy"], actions: ["Apply for Cyber Essentials (est. 4–6 weeks)", "Create IT security policy"] },
    { id: "financials", name: "Financial Health", status: "green", score: 78, issues: [], actions: [] },
    { id: "social-value", name: "Social Value", status: "amber", score: 55, issues: ["No formal social value strategy", "No apprenticeship programme"], actions: ["Create social value policy", "Consider apprenticeship levy usage"] },
    { id: "esg", name: "ESG & Environment", status: "amber", score: 60, issues: ["No formal carbon reduction plan", "No Scope 3 emissions data"], actions: ["Produce net-zero roadmap", "Measure Scope 3 emissions"] },
    { id: "experience", name: "Experience & References", status: "green", score: 85, issues: [], actions: [] },
    { id: "highways", name: "Highways Readiness", status: "green", score: 88, issues: [], actions: ["Renew StreetWorks licence by March 2027"] },
  ]
}

export const DEMO_STATS: DashboardStats = {
  readinessScore: 72,
  matchedOpportunities: 14,
  activeBids: 3,
  upcomingDeadlines: 4,
  complianceGaps: 5,
  pipelineValue: 4_200_000,
  estimatedWinRate: 34,
  renewalsDue: 2,
}

export const DEMO_TENDERS: Tender[] = [
  {
    id: "t-001",
    title: "A57 Road Resurfacing and Drainage Improvement — 3 Year Framework",
    buyer: "National Highways",
    buyerType: "highways",
    location: "Sheffield, South Yorkshire",
    region: "Yorkshire & Humber",
    value: 850_000,
    valueMax: 1_200_000,
    deadline: "2026-07-18",
    publishedDate: "2026-06-01",
    category: "highways",
    type: "framework",
    status: "open",
    recommendation: "recommended",
    opportunityScore: 87,
    eligibilityScore: 82,
    smeFlag: true,
    description: "National Highways seeks an SME-capable contractor to deliver resurfacing, drainage and line marking works on the A57 corridor. Strong social value weighting.",
    cpvCode: "45233141-9",
    reference: "NH/YH/2026/0714",
    socialValueWeighting: 20,
    framework: "Regional Highways Maintenance Framework",
    isDemo: true,
  },
  {
    id: "t-002",
    title: "Winter Maintenance Services — Gritting and Snow Clearance",
    buyer: "Stockport Metropolitan Borough Council",
    buyerType: "local-authority",
    location: "Stockport, Greater Manchester",
    region: "North West",
    value: 340_000,
    deadline: "2026-07-25",
    publishedDate: "2026-06-10",
    category: "highways",
    type: "contract",
    status: "open",
    recommendation: "recommended",
    opportunityScore: 81,
    eligibilityScore: 90,
    smeFlag: true,
    description: "Three-year contract for winter gritting, snow clearance and reactive maintenance across the Stockport highway network.",
    isDemo: true,
  },
  {
    id: "t-003",
    title: "Facilities Management — NHS Greater Manchester Estates",
    buyer: "NHS Greater Manchester ICB",
    buyerType: "nhs",
    location: "Manchester",
    region: "North West",
    value: 1_200_000,
    deadline: "2026-08-05",
    publishedDate: "2026-06-12",
    category: "facilities",
    type: "contract",
    status: "open",
    recommendation: "maybe",
    opportunityScore: 61,
    eligibilityScore: 55,
    smeFlag: false,
    description: "Hard FM services across 12 NHS estates sites including planned and reactive maintenance, grounds and cleaning.",
    socialValueWeighting: 15,
    isDemo: true,
  },
  {
    id: "t-004",
    title: "Street Lighting Maintenance and LED Upgrade",
    buyer: "Leeds City Council",
    buyerType: "local-authority",
    location: "Leeds, West Yorkshire",
    region: "Yorkshire & Humber",
    value: 620_000,
    deadline: "2026-07-30",
    publishedDate: "2026-06-08",
    category: "maintenance",
    type: "contract",
    status: "open",
    recommendation: "recommended",
    opportunityScore: 79,
    eligibilityScore: 74,
    smeFlag: true,
    description: "Maintenance and upgrade of 28,000 street lighting units across Leeds, including LED conversion and smart controls.",
    isDemo: true,
  },
  {
    id: "t-005",
    title: "Commercial Cleaning — Education Cluster Framework",
    buyer: "Academies Enterprise Trust",
    buyerType: "education",
    location: "East Midlands",
    region: "East Midlands",
    value: 180_000,
    deadline: "2026-08-15",
    publishedDate: "2026-06-15",
    category: "cleaning",
    type: "framework",
    status: "open",
    recommendation: "maybe",
    opportunityScore: 58,
    eligibilityScore: 70,
    smeFlag: true,
    description: "Daily cleaning services across 8 academy schools in the East Midlands. Safeguarding clearance required for all staff.",
    isDemo: true,
  },
  {
    id: "t-006",
    title: "M60 Smart Motorway Emergency Barrier Maintenance",
    buyer: "National Highways",
    buyerType: "highways",
    location: "Greater Manchester",
    region: "North West",
    value: 2_100_000,
    deadline: "2026-08-22",
    publishedDate: "2026-06-18",
    category: "highways",
    type: "contract",
    status: "open",
    recommendation: "not-recommended",
    opportunityScore: 38,
    eligibilityScore: 30,
    smeFlag: false,
    description: "Emergency and planned maintenance of Highways England safety barriers on the M60 ring road. Requires NHSS/RSTA accreditation.",
    isDemo: true,
  },
]

export const DEMO_BIDS: Bid[] = [
  {
    id: "b-001",
    tenderId: "t-001",
    tenderTitle: "A57 Road Resurfacing and Drainage Improvement",
    buyer: "National Highways",
    value: 950_000,
    deadline: "2026-07-18",
    stage: "bid-in-progress",
    assignedTo: "Sarah Mitchell",
    probability: 65,
    notes: "Strong match. AI scored our first draft at 71/100. Improving social value section.",
    isDemo: true,
  },
  {
    id: "b-002",
    tenderId: "t-002",
    tenderTitle: "Winter Maintenance Services — Gritting and Snow Clearance",
    buyer: "Stockport MBC",
    value: 340_000,
    deadline: "2026-07-25",
    stage: "qualified",
    assignedTo: "James Reid",
    probability: 70,
    notes: "We hold this contract currently — renewal bid. High win probability.",
    isDemo: true,
  },
  {
    id: "b-003",
    tenderId: "t-004",
    tenderTitle: "Street Lighting Maintenance and LED Upgrade",
    buyer: "Leeds City Council",
    value: 620_000,
    deadline: "2026-07-30",
    stage: "identified",
    assignedTo: "Unassigned",
    probability: 45,
    notes: "New category. Need to check subcontractor for LED installation.",
    isDemo: true,
  },
  {
    id: "b-004",
    tenderId: "ext-001",
    tenderTitle: "M62 Junction 12 Maintenance Works",
    buyer: "National Highways",
    value: 1_800_000,
    deadline: "2026-05-10",
    submittedDate: "2026-05-08",
    stage: "submitted",
    assignedTo: "Sarah Mitchell",
    probability: 40,
    notes: "Submitted. Awaiting evaluation result.",
    isDemo: true,
  },
  {
    id: "b-005",
    tenderId: "ext-002",
    tenderTitle: "Trafford Council Highway Repairs 2025",
    buyer: "Trafford Council",
    value: 280_000,
    deadline: "2026-04-20",
    submittedDate: "2026-04-18",
    awardedDate: "2026-06-01",
    stage: "awarded",
    score: 82,
    assignedTo: "James Reid",
    probability: 100,
    notes: "WON! Contract starts August 2026. £280k over 12 months.",
    isDemo: true,
  },
]

export const DEMO_CONTRACTS: Contract[] = [
  {
    id: "c-001",
    title: "Trafford Council Highway Repairs 2025",
    buyer: "Trafford Council",
    value: 280_000,
    startDate: "2026-08-01",
    endDate: "2027-07-31",
    renewalDate: "2027-05-01",
    isDemo: true,
    milestones: [
      { id: "m-1", title: "Mobilisation complete", dueDate: "2026-08-15", status: "pending" },
      { id: "m-2", title: "Phase 1 — Priority defects", dueDate: "2026-09-30", status: "pending", value: 80_000 },
      { id: "m-3", title: "Phase 2 — Planned resurfacing", dueDate: "2026-11-30", status: "pending", value: 120_000 },
      { id: "m-4", title: "Phase 3 — Line marking", dueDate: "2027-02-28", status: "pending", value: 50_000 },
      { id: "m-5", title: "Final completion", dueDate: "2027-07-31", status: "pending", value: 30_000 },
    ],
    kpis: [
      { id: "k-1", name: "Defect repair time (Cat 1)", target: 2, current: 0, unit: "hours", status: "green" },
      { id: "k-2", name: "Customer satisfaction", target: 85, current: 0, unit: "%", status: "green" },
      { id: "k-3", name: "Local employment", target: 60, current: 0, unit: "% local workforce", status: "amber" },
    ],
    paymentSchedule: [
      { id: "p-1", description: "Mobilisation payment", amount: 15_000, dueDate: "2026-08-31", status: "pending" },
      { id: "p-2", description: "Phase 1 completion", amount: 80_000, dueDate: "2026-10-15", status: "pending" },
    ],
    risks: [
      { id: "r-1", description: "Material price inflation", likelihood: "medium", impact: "medium", mitigation: "Fixed-price materials order placed" },
      { id: "r-2", description: "Labour availability summer 2026", likelihood: "low", impact: "medium", mitigation: "Sub-contractor framework in place" },
    ]
  }
]

export const DEMO_DOCUMENTS: Document[] = [
  { id: "d-001", name: "Public Liability Insurance — £10m", category: "insurance", uploadedDate: "2026-01-10", expiryDate: "2027-01-09", status: "valid", isDemo: true },
  { id: "d-002", name: "Employers Liability Insurance", category: "insurance", uploadedDate: "2026-01-10", expiryDate: "2027-01-09", status: "valid", isDemo: true },
  { id: "d-003", name: "Professional Indemnity — £2m", category: "insurance", uploadedDate: "2026-01-10", expiryDate: "2026-12-31", status: "expiring-soon", isDemo: true },
  { id: "d-004", name: "Health & Safety Policy 2026", category: "policy", uploadedDate: "2026-03-01", expiryDate: "2027-03-01", status: "valid", isDemo: true },
  { id: "d-005", name: "GDPR / Data Protection Policy", category: "policy", uploadedDate: "2024-11-01", expiryDate: "2025-11-01", status: "expired", isDemo: true },
  { id: "d-006", name: "ISO 9001 Certificate", category: "certification", uploadedDate: "2025-04-01", expiryDate: "2028-04-01", status: "valid", isDemo: true },
  { id: "d-007", name: "ISO 14001 Environmental Certificate", category: "certification", uploadedDate: "2025-04-01", expiryDate: "2028-04-01", status: "valid", isDemo: true },
  { id: "d-008", name: "Safe Contractor Certificate", category: "certification", uploadedDate: "2026-02-01", expiryDate: "2027-02-01", status: "valid", isDemo: true },
  { id: "d-009", name: "Cyber Essentials Certificate", category: "certification", uploadedDate: "", expiryDate: "", status: "missing", isDemo: true },
  { id: "d-010", name: "Modern Slavery Statement 2026", category: "policy", uploadedDate: "2026-04-01", status: "valid", isDemo: true },
  { id: "d-011", name: "Company Accounts 2024/25", category: "financial", uploadedDate: "2026-01-15", status: "valid", isDemo: true },
  { id: "d-012", name: "Case Study — M60 Lane Repairs", category: "case-study", uploadedDate: "2025-09-01", status: "valid", isDemo: true },
]

export const DEMO_EVIDENCE: Evidence[] = [
  { id: "e-001", title: "M60 Phase 1 — Before/After Photos", contractId: "ext-001", type: "photo", date: "2025-08-15", description: "Photo evidence of carriageway defect repair and quality", isDemo: true },
  { id: "e-002", title: "KPI Report — Q3 2025 Trafford", contractId: "c-001", type: "kpi-report", date: "2025-10-01", description: "Quarterly KPI performance report achieving 94% satisfaction", isDemo: true },
  { id: "e-003", title: "Client Testimonial — Trafford Council", contractId: "c-001", type: "testimonial", date: "2026-01-10", description: "Written testimonial from contract manager confirming excellent delivery", isDemo: true },
]

export const DEMO_PARTNERS: Partner[] = [
  { id: "p-001", name: "Brightstone Electrical Ltd", sector: "Electrical / Street Lighting", capabilities: ["LED installation", "EV charging", "Smart controls"], region: "Yorkshire & Humber", accreditations: ["iso-9001", "safe-contractor"], turnover: 1_200_000, combinedScore: 84, isDemo: true },
  { id: "p-002", name: "CleanRoute Services", sector: "Cleaning & Facilities", capabilities: ["Commercial cleaning", "Grounds maintenance", "Waste management"], region: "North West", accreditations: ["iso-9001", "iso-14001", "safe-contractor"], turnover: 800_000, combinedScore: 78, isDemo: true },
  { id: "p-003", name: "Digisec IT Solutions", sector: "IT & Cyber", capabilities: ["Cyber security", "Network infrastructure", "Managed services"], region: "East Midlands", accreditations: ["iso-27001", "cyber-essentials-plus"], turnover: 2_100_000, combinedScore: 91, isDemo: true },
]

export const DEMO_BUYERS: Buyer[] = [
  {
    id: "by-001",
    name: "National Highways",
    type: "highways",
    region: "National",
    annualSpend: 2_800_000_000,
    previousAwards: [
      { title: "M60 Maintenance Bundle 2025", supplier: "Balfour Beatty", value: 48_000_000, awardedDate: "2025-03-01", renewalDate: "2028-03-01" },
      { title: "A57 Corridor Works 2024", supplier: "Greenfield Infrastructure Ltd", value: 850_000, awardedDate: "2024-07-01", renewalDate: "2027-07-01" },
    ],
    upcomingRenewals: ["Regional Highways Maintenance Framework Q3 2026", "North West Drainage Framework 2027"],
    knownSuppliers: ["Balfour Beatty", "Amey", "Kier", "Greenfield Infrastructure Ltd"],
    nextTenderExpected: "2026-09-01",
    isDemo: true,
  },
  {
    id: "by-002",
    name: "Stockport Metropolitan Borough Council",
    type: "local-authority",
    region: "North West",
    annualSpend: 180_000_000,
    previousAwards: [
      { title: "Winter Maintenance 2023–26", supplier: "Greenfield Infrastructure Ltd", value: 340_000, awardedDate: "2023-08-01", renewalDate: "2026-07-31" },
    ],
    upcomingRenewals: ["Winter Maintenance Contract 2026–29", "Highway Reactive Maintenance 2027"],
    knownSuppliers: ["Greenfield Infrastructure Ltd", "Amey", "Skanska"],
    nextTenderExpected: "2026-07-25",
    isDemo: true,
  },
]

export const DEMO_CALENDAR: CalendarEvent[] = [
  { id: "ce-001", title: "A57 Resurfacing Bid Deadline", date: "2026-07-18", type: "deadline", tenderId: "t-001", isDemo: true },
  { id: "ce-002", title: "Winter Maintenance Bid Deadline", date: "2026-07-25", type: "deadline", tenderId: "t-002", isDemo: true },
  { id: "ce-003", title: "Street Lighting Bid Deadline", date: "2026-07-30", type: "deadline", tenderId: "t-004", isDemo: true },
  { id: "ce-004", title: "Professional Indemnity Renewal", date: "2026-12-31", type: "doc-expiry", documentId: "d-003", isDemo: true },
  { id: "ce-005", title: "GDPR Policy Renewal (OVERDUE)", date: "2025-11-01", type: "doc-expiry", documentId: "d-005", isDemo: true },
  { id: "ce-006", title: "Trafford Contract Renewal Window Opens", date: "2027-05-01", type: "renewal", isDemo: true },
  { id: "ce-007", title: "NHS Greater Manchester Meet the Buyer", date: "2026-07-10", type: "meet-the-buyer", isDemo: true },
  { id: "ce-008", title: "Construction SME Grant Deadline", date: "2026-08-01", type: "grant", isDemo: true },
]
